### ISSUE TITLE
flannel_iface is broken on k8s 1.16

### ISSUE THREAD

**Issue by rgl** [rancher/kontainer-driver-metadata#55]
due to tabs being at:

https://github.com/rancher/kontainer-driver-metadata/blob/e6d8f524e4456635d1d37a05f2e454a468ed11b6/rke/templates/flannel.go#L642-L644

the `flannel_iface` configuration and flannel is broken when the rke cluster.yaml is:

```yaml
cluster_name: example
kubernetes_version: v1.16.0-beta.1-rancher2-1
network:
  plugin: flannel
  options:
    flannel_iface: eth1
```

the bug was introduced at https://github.com/rancher/kontainer-driver-metadata/commit/10592a4f69a2c3b30855e8e0cf5f4a6ceefeba96.
